/* Original procedural score and effects. No network, media downloads or audio loops. */
window.EmpireAudio = (() => {
 let ac,master,music,effects,on=false,next=0,beat=0,lastStage=-1,active=false;
 const cultures=window.EmpireArt.cultures;
 function init(){try{ac??=new(window.AudioContext||window.webkitAudioContext)();if(!master){master=ac.createGain();master.gain.value=0;master.connect(ac.destination);music=ac.createGain();music.gain.value=.5;music.connect(master);effects=ac.createGain();effects.gain.value=.7;effects.connect(master);}ac.resume();return true;}catch{return false;}}
 function note(freq,at,duration,volume,type='triangle',bus=music){if(!ac)return;const o=ac.createOscillator(),g=ac.createGain();o.type=type;o.frequency.setValueAtTime(freq,at);g.gain.setValueAtTime(0,at);g.gain.linearRampToValueAtTime(volume,at+.015);g.gain.exponentialRampToValueAtTime(.0001,at+duration);o.connect(g);g.connect(bus);o.start(at);o.stop(at+duration+.02);o.onended=()=>{o.disconnect();g.disconnect();};}
 function drum(at,volume=.14){if(!ac)return;const o=ac.createOscillator(),g=ac.createGain();o.frequency.setValueAtTime(130,at);o.frequency.exponentialRampToValueAtTime(42,at+.12);g.gain.setValueAtTime(volume,at);g.gain.exponentialRampToValueAtTime(.0001,at+.17);o.connect(g);g.connect(music);o.start(at);o.stop(at+.18);o.onended=()=>{o.disconnect();g.disconnect();};}
 function setEnabled(value){if(value&&!init())return false;on=value;if(master){master.gain.cancelScheduledValues(ac.currentTime);master.gain.setTargetAtTime(on?.45:0,ac.currentTime,.025);}next=ac?.currentTime||0;return on;}
 function update(stage,phase){if(!on||!ac)return;const playing=phase==='running'||phase==='battle';if(!playing){if(active){music.gain.setTargetAtTime(0,ac.currentTime,.08);active=false;}return;}if(!active||stage!==lastStage){active=true;lastStage=stage;beat=0;next=ac.currentTime;music.gain.setTargetAtTime(.5,ac.currentTime,.06);}if(next<ac.currentTime-.2)next=ac.currentTime;
 const step=phase==='battle'?.21:.29;while(next<ac.currentTime+.08){const root=[146.83,164.81,138.59,130.81,110][stage],melody=cultures[stage].notes;note(root*2**(melody[beat%8]/12)*2,next,.25,.095,stage===2?'sine':'triangle');if(beat%4===0){note(root,next,.95,.1,'sine');drum(next);}if(beat%4===2)drum(next,.07);beat++;next+=step;}}
 function fx(kind){if(!on||!ac)return;const t=ac.currentTime;const melodies={grow:[440,554,659],rescue:[523,659,784,1046],shield:[740,1108,1480],hit:[130,85],rally:[220,330,440,660],win:[392,494,587,784],lose:[294,247,196],start:[294,392,494]};(melodies[kind]||melodies.grow).forEach((f,i)=>note(f,t+i*.07,kind==='win'?.4:.2,.13,kind==='hit'?'sawtooth':'triangle',effects));}
 return {setEnabled,update,fx};
})();
